apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: teste-2
  labels:
    name: pod-2
    app: pod-2
spec:
  containers:
  - name: pod-2-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
