apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: pod-1
    app: pod-1
spec:
  containers:
  - name: pod-1-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: pod-1
  ports:
  - port: 80
    #targetPort: 80
    nodePort: 30000
