apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: segundo-volume
      resources:
        limits:
          cpu: "50m"
          memory: "100Mi"
    - name: jenkins-container
      image: jenkins:2.60.3-alpine
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: segundo-volume
      resources:
        limits:
          cpu: "50m"
          memory: "100Mi"
  volumes:
    - name: segundo-volume
      hostPath:
        path: /home/segundo-volume
        type: DirectoryOrCreate