apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  template:
    metadata: 
      name: portal-noticias
      labels:
        name: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
  minReadySeconds: 0
  replicas: 2
  selector:
    matchLabels:
      name: portal-noticias