apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
spec:
  template:
    metadata:
      name: db-portal-noticias
      labels:
        name: db-portal-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          resources:
            limits:
              memory: "500Mi"
              cpu: "250m"
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
  replicas: 1
  minReadySeconds: 0
  selector:
    matchLabels:
      name: db-portal-noticias
  
  