apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    name: portal-noticias
spec:
  containers:
    - name: portal-noticias-container
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
