apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-noticias-deployment
spec:
  template:
    metadata:
      name: sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
      - name: sistema-noticias-container
        image: aluracursos/sistema-noticias:1
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: sistema-configmap
        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 3
  minReadySeconds: 0
  replicas: 1
  selector:
    matchLabels:
      app: sistema-noticias