apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  template:
    metadata: 
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
      - name: portal-noticias-container
        image: aluracursos/portal-noticias:1
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        envFrom:
          - configMapRef:
              name: portal-configmap
        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 3
  minReadySeconds: 0
  replicas: 2
  selector:
    matchLabels:
      app: portal-noticias